import { Currency, Rates } from './types';

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'Dólar Estadounidense', flag: '🇺🇸', symbol: '$' },
  { code: 'PEN', name: 'Sol Peruano', flag: '🇵🇪', symbol: 'S/.' },
  { code: 'EUR', name: 'Euro', flag: '🇪🇺', symbol: '€' },
  { code: 'GBP', name: 'Libra Esterlina', flag: '🇬🇧', symbol: '£' },
  { code: 'JPY', name: 'Yen Japonés', flag: '🇯🇵', symbol: '¥' },
  { code: 'CAD', name: 'Dólar Canadiense', flag: '🇨🇦', symbol: 'C$' },
  { code: 'AUD', name: 'Dólar Australiano', flag: '🇦🇺', symbol: 'A$' },
  { code: 'CHF', name: 'Franco Suizo', flag: '🇨🇭', symbol: 'CHF' },
  { code: 'CNY', name: 'Yuan Chino', flag: '🇨🇳', symbol: '¥' },
  { code: 'INR', name: 'Rupia India', flag: '🇮🇳', symbol: '₹' },
  { code: 'MXN', name: 'Peso Mexicano', flag: '🇲🇽', symbol: '$' },
  { code: 'ARS', name: 'Peso Argentino', flag: '🇦🇷', symbol: '$' },
  { code: 'COP', name: 'Peso Colombiano', flag: '🇨🇴', symbol: '$' },
  { code: 'BRL', name: 'Real Brasileño', flag: '🇧🇷', symbol: 'R$' },
  { code: 'BOB', name: 'Boliviano', flag: '🇧🇴', symbol: 'Bs' },
  { code: 'CLP', name: 'Peso Chileno', flag: '🇨🇱', symbol: '$' },
  { code: 'UYU', name: 'Peso Uruguayo', flag: '🇺🇾', symbol: '$U' },
  { code: 'VES', name: 'Bolívar Venezolano', flag: '🇻🇪', symbol: 'Bs.F' },
  { code: 'PYG', name: 'Guaraní Paraguayo', flag: '🇵🇾', symbol: '₲' },
  { code: 'CRC', name: 'Colón Costarricense', flag: '🇨🇷', symbol: '₡' },
  { code: 'DOP', name: 'Peso Dominicano', flag: '🇩🇴', symbol: 'RD$' },
  { code: 'GTQ', name: 'Quetzal Guatemalteco', flag: '🇬🇹', symbol: 'Q' },
  { code: 'HNL', name: 'Lempira Hondureño', flag: '🇭🇳', symbol: 'L' },
  { code: 'NIO', name: 'Córdoba Nicaragüense', flag: '🇳🇮', symbol: 'C$' },
  { code: 'PAB', name: 'Balboa Panameño', flag: '🇵🇦', symbol: 'B/.' },
  { code: 'PKR', name: 'Rupia Pakistaní', flag: '🇵🇰', symbol: '₨' },
  { code: 'KRW', name: 'Won Surcoreano', flag: '🇰🇷', symbol: '₩' },
  { code: 'SGD', name: 'Dólar Singapurense', flag: '🇸🇬', symbol: 'S$' },
  { code: 'AED', name: 'Dirham de Emiratos Árabes', flag: '🇦🇪', symbol: 'د.إ' },
  { code: 'ZAR', name: 'Rand Sudafricano', flag: '🇿🇦', symbol: 'R' }
];

export const FALLBACK_RATES: Rates = {
  USD: 1.0,
  PEN: 3.7350,
  EUR: 0.9220,
  GBP: 0.7850,
  JPY: 156.2000,
  CAD: 1.3680,
  AUD: 1.5050,
  CHF: 0.8980,
  CNY: 7.2400,
  INR: 83.5000,
  MXN: 17.8200,
  ARS: 885.0000,
  COP: 3950.0000,
  BRL: 5.1200,
  BOB: 6.9100,
  CLP: 921.0000,
  UYU: 38.8000,
  VES: 36.4000,
  PYG: 7520.0000,
  CRC: 512.0000,
  DOP: 59.1000,
  GTQ: 7.7600,
  HNL: 24.6800,
  NIO: 36.7800,
  PAB: 1.0000,
  PKR: 278.4000,
  KRW: 1375.0000,
  SGD: 1.3480,
  AED: 3.6720,
  ZAR: 18.2500
};
