import { Currency, Rates } from './types';

export const CURRENCIES: Currency[] = [
  { code: 'USD', name: 'Dólar Estadounidense', flag: '🇺🇸', symbol: '$', countries: ['Estados Unidos', 'Ecuador', 'El Salvador', 'Panamá', 'Puerto Rico', 'Palau', 'Micronesia', 'Islas Marshall', 'USA', 'EEUU'] },
  { code: 'PEN', name: 'Sol Peruano', flag: '🇵🇪', symbol: 'S/.', countries: ['Perú', 'Peru'] },
  { code: 'EUR', name: 'Euro', flag: '🇪🇺', symbol: '€', countries: ['Alemania', 'Francia', 'Italia', 'España', 'Portugal', 'Países Bajos', 'Bélgica', 'Austria', 'Grecia', 'Finlandia', 'Irlanda', 'Eslovaquia', 'Croacia', 'Eslovenia', 'Chipre', 'Estonia', 'Letonia', 'Lituania', 'Luxemburgo', 'Malta', 'Europa', 'Espana', 'Paises Bajos'] },
  { code: 'GBP', name: 'Libra Esterlina', flag: '🇬🇧', symbol: '£', countries: ['Reino Unido', 'Gran Bretaña', 'Inglaterra', 'Escocia', 'Gales', 'Irlanda del Norte', 'Gibraltar', 'UK'] },
  { code: 'JPY', name: 'Yen Japonés', flag: '🇯🇵', symbol: '¥', countries: ['Japón', 'Japon'] },
  { code: 'CAD', name: 'Dólar Canadiense', flag: '🇨🇦', symbol: 'C$', countries: ['Canadá', 'Canada'] },
  { code: 'AUD', name: 'Dólar Australiano', flag: '🇦🇺', symbol: 'A$', countries: ['Australia', 'Kiribati', 'Nauru', 'Tuvalu'] },
  { code: 'CHF', name: 'Franco Suizo', flag: '🇨🇭', symbol: 'CHF', countries: ['Suiza', 'Liechtenstein'] },
  { code: 'CNY', name: 'Yuan Chino', flag: '🇨🇳', symbol: '¥', countries: ['China'] },
  { code: 'INR', name: 'Rupia India', flag: '🇮🇳', symbol: '₹', countries: ['India', 'Bután', 'Butan'] },
  { code: 'MXN', name: 'Peso Mexicano', flag: '🇲🇽', symbol: '$', countries: ['México', 'Mexico'] },
  { code: 'ARS', name: 'Peso Argentino', flag: '🇦🇷', symbol: '$', countries: ['Argentina'] },
  { code: 'COP', name: 'Peso Colombiano', flag: '🇨🇴', symbol: '$', countries: ['Colombia'] },
  { code: 'BRL', name: 'Real Brasileño', flag: '🇧🇷', symbol: 'R$', countries: ['Brasil', 'Brazil'] },
  { code: 'BOB', name: 'Boliviano', flag: '🇧🇴', symbol: 'Bs', countries: ['Bolivia'] },
  { code: 'CLP', name: 'Peso Chileno', flag: '🇨🇱', symbol: '$', countries: ['Chile'] },
  { code: 'UYU', name: 'Peso Uruguayo', flag: '🇺🇾', symbol: '$U', countries: ['Uruguay'] },
  { code: 'VES', name: 'Bolívar Venezolano', flag: '🇻🇪', symbol: 'Bs.F', countries: ['Venezuela'] },
  { code: 'PYG', name: 'Guaraní Paraguayo', flag: '🇵🇾', symbol: '₲', countries: ['Paraguay'] },
  { code: 'CRC', name: 'Colón Costarricense', flag: '🇨🇷', symbol: '₡', countries: ['Costa Rica'] },
  { code: 'DOP', name: 'Peso Dominicano', flag: '🇩🇴', symbol: 'RD$', countries: ['República Dominicana', 'Republica Dominicana', 'Santo Domingo'] },
  { code: 'GTQ', name: 'Quetzal Guatemalteco', flag: '🇬🇹', symbol: 'Q', countries: ['Guatemala'] },
  { code: 'HNL', name: 'Lempira Hondureño', flag: '🇭🇳', symbol: 'L', countries: ['Honduras'] },
  { code: 'NIO', name: 'Córdoba Nicaragüense', flag: '🇳🇮', symbol: 'C$', countries: ['Nicaragua'] },
  { code: 'PAB', name: 'Balboa Panameño', flag: '🇵🇦', symbol: 'B/.', countries: ['Panamá', 'Panama'] },
  { code: 'PKR', name: 'Rupia Pakistaní', flag: '🇵🇰', symbol: '₨', countries: ['Pakistán', 'Pakistan'] },
  { code: 'KRW', name: 'Won Surcoreano', flag: '🇰🇷', symbol: '₩', countries: ['Corea del Sur', 'Corea'] },
  { code: 'SGD', name: 'Dólar Singapurense', flag: '🇸🇬', symbol: 'S$', countries: ['Singapur', 'Singapore'] },
  { code: 'AED', name: 'Dirham de Emiratos Árabes', flag: '🇦🇪', symbol: 'د.إ', countries: ['Emiratos Árabes Unidos', 'Emiratos Arabes', 'Dubái', 'Dubai', 'Abu Dabi', 'Abu Dhabi'] },
  { code: 'ZAR', name: 'Rand Sudafricano', flag: '🇿🇦', symbol: 'R', countries: ['Sudáfrica', 'Sudafrica', 'Namibia', 'Lesoto', 'Esuatini'] }
];

export const FALLBACK_RATES: Rates = {
  USD: 1.0,
  PEN: 3.7350,
  EUR: 0.9220,
  GBP: 0.7850,
  JPY: 156.2000,
  CAD: 1.3680,
  AUD: 1.5050,
  CHF: 0.8980,
  CNY: 7.2400,
  INR: 83.5000,
  MXN: 17.8200,
  ARS: 885.0000,
  COP: 3950.0000,
  BRL: 5.1200,
  BOB: 6.9100,
  CLP: 921.0000,
  UYU: 38.8000,
  VES: 36.4000,
  PYG: 7520.0000,
  CRC: 512.0000,
  DOP: 59.1000,
  GTQ: 7.7600,
  HNL: 24.6800,
  NIO: 36.7800,
  PAB: 1.0000,
  PKR: 278.4000,
  KRW: 1375.0000,
  SGD: 1.3480,
  AED: 3.6720,
  ZAR: 18.2500
};
